### ISSUE TITLE
Fails when trying to convert any python file

### ISSUE THREAD

**Issue by karadagi** [uxmal/pytocs#20] opened 2018-04-11 09:28 UTC
I just wrote _pytocs hello.py_ and took the error below:
System.InvalidOperationException: '-(1): Expected token type NEWLINE, but saw ID.'

**Comment by uxmal** [comment] 2018-04-12 20:00
I'm unable to reproduce this error. What platform are you running on? How did you compile pytocs? Could you supply me with a copy of the `hello.py` file you are using in a ZIP file? Just drag the ZIP file into a comment field below.

**Comment by karadagi** [comment] 2018-04-12 22:37
Thanks for your reply. I am using Windows 10. For compiling, I just open src/pytocs.sln in Microsoft Visual Studio and just click run. Then the command line is being opened and I just drag and drop hello.py file that you supplied. I have also converted it to zip file and drag&drop but no luck.

**Comment by karadagi** [comment] 2018-04-12 22:45
![image](https://user-images.githubusercontent.com/22752273/38707937-4e049844-3ebc-11e8-86de-1d825ff82115.png)

**Comment by karadagi** [comment] 2018-04-12 22:54
![image](https://user-images.githubusercontent.com/22752273/38707986-a1469070-3ebc-11e8-96ae-5375f3a752a2.png)

**Comment by uxmal** [comment] 2018-04-15 11:12
We resolved the issue on your machine. I'm closing this now and looking at the next issue.

**Closed as completed by uxmal** 2018-04-15 11:12 UTC
